apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-metric-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-metric-app
  template:
    metadata:
      labels:
        app: go-metric-app
    spec:
      containers:
      - name: go-metric-app
        image: ozanncakar/go-metric-app:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: go-metric-app-service
spec:
  type: NodePort
  selector:
    app: go-metric-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30001

