apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-otel-collector-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-otel-collector-demo-app
  template:
    metadata:
      labels:
        app: dotnet-otel-collector-demo-app
    spec:
      containers:
      - name: dotnet-otel-collector-demo-app
        image: ozanncakar/dotnet-otel-collector-demo:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-otel-collector-demo-app-service
spec:
  type: NodePort
  selector:
    app: dotnet-otel-collector-demo-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30001

