# Basic OpenTelemetry Collector confugiration
mode: deployment
replicaCount: 1

image:
  repository: otel/opentelemetry-collector-contrib
  tag: "latest"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# OpenTelemetry Collector Confugirations
config:
  receivers:

    hostmetrics:
# The hostmetrics receiver collects metrics from the host system
      scrapers:
        cpu:
        disk:
        filesystem:
        load:
        memory:
        network:

# Prometheus receiver configuration for scraping metrics from the OpenTelemetry Collector itself 
    prometheus:
      config:
        scrape_configs:
          - job_name: "otelcol"
            scrape_interval: 10s
            static_configs:
              - targets: ["0.0.0.0:8888"]


    # OTLP receiver - to receive metrics from applications
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    batch: {}

  exporters:
    # Provides metrics in Prometheus format
    prometheus:
      endpoint: "0.0.0.0:8889"


  service:
    pipelines:
      metrics:
        receivers: [otlp, hostmetrics]
        processors: [batch]
        exporters: [prometheus]
