mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: latest

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

config:
  receivers:
    otlp:  # Uygulamalardan veri almak için OTLP protokolü (OpenTelemetry Protocol)
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317

        http:
          endpoint: 0.0.0.0:4318


  processors:
    batch: {}  # Gelen veriler topluca işlenip gönderilir (daha verimli)

  exporters:
    prometheus:  # Prometheus’un scrape edebileceği HTTP endpoint tanımı
      endpoint: "0.0.0.0:8889"  # Collector bu porttan metriklerini açar (/metrics)

  service:
    telemetry:
      metrics:
        address: "0.0.0.0:8888"
    pipelines:
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [prometheus]