apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-erlang-cookie
  namespace: default
type: Opaque
data:
  erl-cookie: bXlzdXBlcnNlY3JldGNvb2tpZQ==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: default
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
          - name: RABBITMQ_ERLANG_COOKIE
            valueFrom:
              secretKeyRef:
                name: rabbitmq-erlang-cookie
                key: erl-cookie
          - name: RABBITMQ_DEFAULT_USER
            value: "admin"
          - name: RABBITMQ_DEFAULT_PASS
            value: "admin"
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
        - name: rabbitmq-logs
          mountPath: /var/log/rabbitmq
      volumes:
      - name: rabbitmq-data
        hostPath:
          path: /path/to/rabbitmq/data
          type: DirectoryOrCreate
      - name: rabbitmq-logs
        hostPath:
          path: /path/to/rabbitmq/logs
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: default
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  ports:
  - port: 5672
    targetPort: 5672
    name: rabbitmq
  - port: 15672
    targetPort: 15672
    name: rabbitmq-web
  selector:
    app: rabbitmq

# LoadBalancer Services - For Distr
###############################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-loadbalancer
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672